- name: demo of vars on play level
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL={{ URL }}

- name: demo of vars on task level
  hosts: localhost
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL={{URL}}
      vars:
        URL: task.example.com
- name: demo of var from vars-files on playlevel
  hosts: localhost
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: "{{URL}}"