- name: demo of vars on play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL={{ URL }}

- name: demo of vars on task level
  hosts: all
  connection: local
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL={{URL}}
      vars:
        URL: task.example.com
- name: demo of var from vars-files on playlevel
  hosts: all
  connection: local
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: "{{URL}}"
- name: demo from inv
  hosts: all
  connection: local
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL={{URL}}
- name: Access fact
  hosts: all
  connection: local
  tasks:
    - name: Print fact
      ansible.builtin.debug:
        msg: "{{ansible_os_family}}"
- name: demo on runtime variable
  hosts: all
  connection: local
  tasks:
    - name: execute list command
      ansible.builtin.shell: uptime
      register: out
    - name: set fact
      ansible.builtin.set_fact:
        UPTIME: "{{out.stdout}}"
    - name: access the runtime variable
      ansible.builtin.debug:
        msg: "{{UPTIME}}"