- name: Demo on conditions
  hosts: localhost
  vars:
    HELLO: hello
  tasks:
    - name: print hello if hello is defined
      ansible.builtin.debug:
        msg: hello
      when: HELLO is defined